{
  "delayTime": 363002,
  "executionTime": 465,
  "id": "62d50584-d6de-462e-a86f-23624266756f-e1",
  "output": {
    "output": {
      "audio": null,
      "chunks": [
        {
          "content": {
            "error": "Error using TTS endpoint: TTS endpoint failed with status 500: Failed to open the input \"Custom Input Context\" (Invalid data found when processing input).\nException raised from get_input_format_context at /__w/audio/audio/pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp:42 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x78052d177f86 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)\nframe #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x78052d126d10 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)\nframe #2: <unknown function> + 0x41ff4 (0x78052d04fff4 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #3: torio::io::StreamingMediaDecoder::StreamingMediaDecoder(AVIOContext*, std::optional<std::string> const&, std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x43 (0x78052d052933 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #4: torio::io::StreamingMediaDecoderCustomIO::StreamingMediaDecoderCustomIO(void*, std::optional<std::string> const&, int, int (*)(void*, unsigned char*, int), long (*)(void*, long, int), std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x2f (0x78052d0529cf in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #5: <unknown function> + 0x1a3ed (0x78046cfd53ed in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)\nframe #6: <unknown function> + 0x32bf7 (0x78046cfedbf7 in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)\nframe #7: python() [0x55563b]\n<omitting python frames>\nframe #9: python() [0x5853dd]\nframe #10: python() [0x56e2a9]\nframe #11: python() [0x52fa70]\nframe #12: <unknown function> + 0xfc1b (0x78052d094c1b in /usr/local/lib/python3.11/dist-packages/torchaudio/lib/_torchaudio.so)\nframe #16: python() [0x56df36]\nframe #19: python() [0x628dc0]\nframe #20: python() [0x62b3cc]\nframe #21: python() [0x56ed5f]\nframe #24: python() [0x5d59ed]\nframe #25: python() [0x55c0ab]\nframe #28: python() [0x628dc0]\nframe #30: python() [0x628dc0]\nframe #32: python() [0x628dc0]\nframe #34: python() [0x628dc0]\nframe #36: python() [0x628dc0]\nframe #38: python() [0x628dc0]\nframe #40: python() [0x628dc0]\nframe #42: python() [0x628dc0]\nframe #44: python() [0x628dc0]\nframe #46: python() [0x628dc0]\nframe #47: <unknown function> + 0x745f (0x7805a42b445f in /usr/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so)\nframe #48: python() [0x553abf]\nframe #49: <unknown function> + 0x5d4ee (0x7803c4e904ee in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #50: <unknown function> + 0x143a98 (0x7803c4f76a98 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #51: <unknown function> + 0x148326 (0x7803c4f7b326 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #52: <unknown function> + 0x143ae0 (0x7803c4f76ae0 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #53: <unknown function> + 0x145370 (0x7803c4f78370 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #54: uv__run_idle + 0x81 (0x7803c4f91691 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #55: uv_run + 0xbd (0x7803c4f8e96d in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #56: <unknown function> + 0xe43f3 (0x7803c4f173f3 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #57: <unknown function> + 0xf0711 (0x7803c4f23711 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #58: <unknown function> + 0xf6592 (0x7803c4f29592 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #59: <unknown function> + 0x10fbbc (0x7803c4f42bbc in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #62: python() [0x613f24]\n",
            "trace": "Traceback (most recent call last):\n  File \"/app/fish-speech/runpod/handler.py\", line 328, in process_request\n    raise RuntimeError(f\"TTS endpoint failed with status {response.status_code}: {error_message}\")\nRuntimeError: TTS endpoint failed with status 500: Failed to open the input \"Custom Input Context\" (Invalid data found when processing input).\nException raised from get_input_format_context at /__w/audio/audio/pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp:42 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x78052d177f86 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)\nframe #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x78052d126d10 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)\nframe #2: <unknown function> + 0x41ff4 (0x78052d04fff4 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #3: torio::io::StreamingMediaDecoder::StreamingMediaDecoder(AVIOContext*, std::optional<std::string> const&, std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x43 (0x78052d052933 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #4: torio::io::StreamingMediaDecoderCustomIO::StreamingMediaDecoderCustomIO(void*, std::optional<std::string> const&, int, int (*)(void*, unsigned char*, int), long (*)(void*, long, int), std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x2f (0x78052d0529cf in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #5: <unknown function> + 0x1a3ed (0x78046cfd53ed in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)\nframe #6: <unknown function> + 0x32bf7 (0x78046cfedbf7 in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)\nframe #7: python() [0x55563b]\n<omitting python frames>\nframe #9: python() [0x5853dd]\nframe #10: python() [0x56e2a9]\nframe #11: python() [0x52fa70]\nframe #12: <unknown function> + 0xfc1b (0x78052d094c1b in /usr/local/lib/python3.11/dist-packages/torchaudio/lib/_torchaudio.so)\nframe #16: python() [0x56df36]\nframe #19: python() [0x628dc0]\nframe #20: python() [0x62b3cc]\nframe #21: python() [0x56ed5f]\nframe #24: python() [0x5d59ed]\nframe #25: python() [0x55c0ab]\nframe #28: python() [0x628dc0]\nframe #30: python() [0x628dc0]\nframe #32: python() [0x628dc0]\nframe #34: python() [0x628dc0]\nframe #36: python() [0x628dc0]\nframe #38: python() [0x628dc0]\nframe #40: python() [0x628dc0]\nframe #42: python() [0x628dc0]\nframe #44: python() [0x628dc0]\nframe #46: python() [0x628dc0]\nframe #47: <unknown function> + 0x745f (0x7805a42b445f in /usr/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so)\nframe #48: python() [0x553abf]\nframe #49: <unknown function> + 0x5d4ee (0x7803c4e904ee in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #50: <unknown function> + 0x143a98 (0x7803c4f76a98 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #51: <unknown function> + 0x148326 (0x7803c4f7b326 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #52: <unknown function> + 0x143ae0 (0x7803c4f76ae0 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #53: <unknown function> + 0x145370 (0x7803c4f78370 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #54: uv__run_idle + 0x81 (0x7803c4f91691 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #55: uv_run + 0xbd (0x7803c4f8e96d in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #56: <unknown function> + 0xe43f3 (0x7803c4f173f3 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #57: <unknown function> + 0xf0711 (0x7803c4f23711 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #58: <unknown function> + 0xf6592 (0x7803c4f29592 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #59: <unknown function> + 0x10fbbc (0x7803c4f42bbc in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #62: python() [0x613f24]\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/fish-speech/runpod/handler.py\", line 357, in process_request\n    raise RuntimeError(f\"Error using TTS endpoint: {str(e)}\")\nRuntimeError: Error using TTS endpoint: TTS endpoint failed with status 500: Failed to open the input \"Custom Input Context\" (Invalid data found when processing input).\nException raised from get_input_format_context at /__w/audio/audio/pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp:42 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x78052d177f86 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)\nframe #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x78052d126d10 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)\nframe #2: <unknown function> + 0x41ff4 (0x78052d04fff4 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #3: torio::io::StreamingMediaDecoder::StreamingMediaDecoder(AVIOContext*, std::optional<std::string> const&, std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x43 (0x78052d052933 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #4: torio::io::StreamingMediaDecoderCustomIO::StreamingMediaDecoderCustomIO(void*, std::optional<std::string> const&, int, int (*)(void*, unsigned char*, int), long (*)(void*, long, int), std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x2f (0x78052d0529cf in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)\nframe #5: <unknown function> + 0x1a3ed (0x78046cfd53ed in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)\nframe #6: <unknown function> + 0x32bf7 (0x78046cfedbf7 in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)\nframe #7: python() [0x55563b]\n<omitting python frames>\nframe #9: python() [0x5853dd]\nframe #10: python() [0x56e2a9]\nframe #11: python() [0x52fa70]\nframe #12: <unknown function> + 0xfc1b (0x78052d094c1b in /usr/local/lib/python3.11/dist-packages/torchaudio/lib/_torchaudio.so)\nframe #16: python() [0x56df36]\nframe #19: python() [0x628dc0]\nframe #20: python() [0x62b3cc]\nframe #21: python() [0x56ed5f]\nframe #24: python() [0x5d59ed]\nframe #25: python() [0x55c0ab]\nframe #28: python() [0x628dc0]\nframe #30: python() [0x628dc0]\nframe #32: python() [0x628dc0]\nframe #34: python() [0x628dc0]\nframe #36: python() [0x628dc0]\nframe #38: python() [0x628dc0]\nframe #40: python() [0x628dc0]\nframe #42: python() [0x628dc0]\nframe #44: python() [0x628dc0]\nframe #46: python() [0x628dc0]\nframe #47: <unknown function> + 0x745f (0x7805a42b445f in /usr/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so)\nframe #48: python() [0x553abf]\nframe #49: <unknown function> + 0x5d4ee (0x7803c4e904ee in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #50: <unknown function> + 0x143a98 (0x7803c4f76a98 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #51: <unknown function> + 0x148326 (0x7803c4f7b326 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #52: <unknown function> + 0x143ae0 (0x7803c4f76ae0 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #53: <unknown function> + 0x145370 (0x7803c4f78370 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #54: uv__run_idle + 0x81 (0x7803c4f91691 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #55: uv_run + 0xbd (0x7803c4f8e96d in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #56: <unknown function> + 0xe43f3 (0x7803c4f173f3 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #57: <unknown function> + 0xf0711 (0x7803c4f23711 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #58: <unknown function> + 0xf6592 (0x7803c4f29592 in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #59: <unknown function> + 0x10fbbc (0x7803c4f42bbc in /usr/local/lib/python3.11/dist-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so)\nframe #62: python() [0x613f24]\n\n"
          },
          "type": "error"
        }
      ],
      "status": "success",
      "text": ""
    }
  },
  "status": "COMPLETED",
  "workerId": "2dgmyjj63unldj"
}